/**********************************************************************
 * Extern for EVT
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var EVT = {
  "App": function () {},
  "Device": function () {},
  "Entity": {
    "Action": function () {},
    "ActionType": function () {},
    "Collection": function () {},
    "Location": function () {},
    "Permission": function () {},
    "Place": function () {},
    "Policy": function () {},
    "Product": function () {},
    "Property": function () {},
    "Role": function () {},
    "Thng": function () {},
    "User": function () {}
  },
  "User": function () {},
  "Utils": {
    "buildParams": function () {},
    "buildUrl": function () {},
    "escapeSpecials": function () {},
    "extend": function () {},
    "extendCurried": function () {},
    "forEachAsync": function () {},
    "getCurrentPosition": function () {},
    "isArray": function () {},
    "isDefined": function () {},
    "isFunction": function () {},
    "isObject": function () {},
    "isString": function () {},
    "parseLinkHeader": function () {},
    "spawn": function () {}
  },
  "api": function () {},
  "settings": {
    "apiUrl": {},
    "fullResponse": {},
    "geolocation": {},
    "interceptors": {},
    "quiet": {}
  },
  "setup": function () {},
  "use": function () {},
  "version": {}
};
EVT.App.prototype = {
  "action": function () {},
  "appUser": function () {},
  "constructor": function () {},
  "login": function () {},
  "place": function () {},
  "product": function () {}
};
EVT.Device.prototype = {
  "action": function () {},
  "constructor": function () {},
  "property": function () {},
  "update": function () {}
};
EVT.Entity.Action.prototype = {
  "constructor": function () {},
  "delete": function () {},
  "toJSON": function () {},
  "update": function () {}
};
EVT.Entity.ActionType.prototype = {
  "constructor": function () {},
  "delete": function () {},
  "toJSON": function () {},
  "update": function () {}
};
EVT.Entity.Collection.prototype = {
  "action": function () {},
  "collection": function () {},
  "constructor": function () {},
  "delete": function () {},
  "thng": function () {},
  "toJSON": function () {},
  "update": function () {}
};
EVT.Entity.Location.prototype = {
  "constructor": function () {},
  "delete": function () {},
  "toJSON": function () {},
  "update": function () {}
};
EVT.Entity.Permission.prototype = {
  "constructor": function () {},
  "delete": function () {},
  "toJSON": function () {},
  "update": function () {}
};
EVT.Entity.Place.prototype = {
  "constructor": function () {},
  "delete": function () {},
  "toJSON": function () {},
  "update": function () {}
};
EVT.Entity.Policy.prototype = {
  "constructor": function () {},
  "delete": function () {},
  "toJSON": function () {},
  "update": function () {}
};
EVT.Entity.Product.prototype = {
  "action": function () {},
  "constructor": function () {},
  "delete": function () {},
  "property": function () {},
  "toJSON": function () {},
  "update": function () {}
};
EVT.Entity.Property.prototype = {
  "constructor": function () {},
  "delete": function () {},
  "toJSON": function () {},
  "update": function () {}
};
EVT.Entity.Role.prototype = {
  "constructor": function () {},
  "delete": function () {},
  "permission": function () {},
  "policy": function () {},
  "toJSON": function () {},
  "update": function () {}
};
EVT.Entity.Thng.prototype = {
  "action": function () {},
  "constructor": function () {},
  "delete": function () {},
  "location": function () {},
  "property": function () {},
  "readProduct": function () {},
  "toJSON": function () {},
  "update": function () {}
};
EVT.Entity.User.prototype = {
  "constructor": function () {},
  "delete": function () {},
  "toJSON": function () {},
  "update": function () {},
  "validate": function () {}
};
EVT.User.prototype = {
  "action": function () {},
  "actionType": function () {},
  "collection": function () {},
  "constructor": function () {},
  "logout": function () {},
  "place": function () {},
  "product": function () {},
  "role": function () {},
  "thng": function () {},
  "update": function () {}
};
/**********************************************************************
 * End Generated Extern for EVT
/**********************************************************************/